@startuml

title __APP's Class Diagram__\n

  namespace com.cleanup.todoc {
    class com.cleanup.todoc.BuildConfig {
    }
  }
  

  namespace com.cleanup.todoc {
    namespace db {
      abstract class com.cleanup.todoc.db.RoomDb {
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace db {
      class com.cleanup.todoc.db.RoomDb_Impl {
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace db {
      interface com.cleanup.todoc.db.TaskDao {
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace db {
      class com.cleanup.todoc.db.TaskDao_Impl {
      }
  }
  

  namespace com.cleanup.todoc {
    namespace model {
      class com.cleanup.todoc.model.Project {
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace model {
      class com.cleanup.todoc.model.Task {
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace ui {
      class com.cleanup.todoc.ui.MainActivity {
      }
    }
  }
  

  namespace com.cleanup.todoc {
    namespace ui {
      class com.cleanup.todoc.ui.TasksAdapter {
      }
    }
  }
  

  com.cleanup.todoc.db.RoomDb -up-|> android.arch.persistence.room.RoomDatabase
  com.cleanup.todoc.db.RoomDb_Impl -up-|> com.cleanup.todoc.db.RoomDb
  com.cleanup.todoc.db.RoomDb_Impl o-- com.cleanup.todoc.db.TaskDao : _taskDao
  com.cleanup.todoc.db.TaskDao_Impl .up.|> com.cleanup.todoc.db.TaskDao
  com.cleanup.todoc.ui.MainActivity .up.|> com.cleanup.todoc.ui.TasksAdapter.DeleteTaskListener
  com.cleanup.todoc.ui.MainActivity -up-|> android.support.v7.app.AppCompatActivity
  com.cleanup.todoc.ui.MainActivity o-- com.cleanup.todoc.ui.TasksAdapter : adapter
  com.cleanup.todoc.ui.MainActivity o-- com.cleanup.todoc.db.RoomDb : roomDb
  com.cleanup.todoc.ui.MainActivity o-- com.cleanup.todoc.ui.MainActivity.SortMethod : sortMethod
  com.cleanup.todoc.ui.TasksAdapter -up-|> android.support.v7.widget.RecyclerView.Adapter
  com.cleanup.todoc.ui.TasksAdapter o-- com.cleanup.todoc.ui.TasksAdapter.DeleteTaskListener : deleteTaskListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
